add_rules("mode.debug", "mode.release")
set_defaultmode("release")

local function xmake_packages_cmake(target)
	local include_dirs = {}
	local link_dirs = {}
	local links = {}

	for _, pkg in pairs(target:pkgs() or {}) do
		for _, dir in ipairs(table.wrap(pkg:get("includedirs") or {})) do
			table.insert(include_dirs, dir)
		end
		for _, dir in ipairs(table.wrap(pkg:get("sysincludedirs") or {})) do
			table.insert(include_dirs, dir)
		end
		for _, dir in ipairs(table.wrap(pkg:get("linkdirs") or {})) do
			table.insert(link_dirs, dir)
		end
		for _, l in ipairs(table.wrap(pkg:get("links") or {})) do
			table.insert(links, l)
		end
		for _, l in ipairs(table.wrap(pkg:get("syslinks") or {})) do
			table.insert(links, l)
		end
	end

	local lines = ""
	if #include_dirs > 0 then
		lines = lines .. "target_include_directories(${PROJECT_NAME} PRIVATE\n"
		for _, d in ipairs(include_dirs) do
			lines = lines .. string.format('    "%s"\n', d:gsub("\\", "/"))
		end
		lines = lines .. ")\n"
	end
	if #link_dirs > 0 then
		lines = lines .. "target_link_directories(${PROJECT_NAME} PRIVATE\n"
		for _, d in ipairs(link_dirs) do
			lines = lines .. string.format('    "%s"\n', d:gsub("\\", "/"))
		end
		lines = lines .. ")\n"
	end
	if #links > 0 then
		lines = lines .. "target_link_libraries(${PROJECT_NAME} PRIVATE\n"
		for _, l in ipairs(links) do
			lines = lines .. string.format('    "%s"\n', l)
		end
		lines = lines .. ")\n"
	end
	return lines
end

rule("geode.mod")

on_load(function(target)
	target:set("kind", "shared")
	target:set("prefixname", "")

	local mod_json_path = path.join(target:scriptdir(), "mod.json")
	if os.isfile(mod_json_path) then
		local raw = io.readfile(mod_json_path)
		local mod_id = raw and raw:match('"id"%s*:%s*"([^"]+)"')
		if mod_id then
			target:set("basename", mod_id)
			target:data_set("geode.mod_id", mod_id)
		end
	end

	if os.host() == "linux" then
		target:set("toolset", "cxx", "clang-cl")
		target:set("toolset", "cc", "clang-cl")
		target:set("toolset", "ld", "lld-link")
		target:set("toolset", "sh", "lld-link")
		target:set("toolset", "ar", "llvm-lib")

		target:add(
			"cxflags",
			"--target=x86_64-windows-msvc",
			"-fms-compatibility-version=19.37",
			"/EHsc",
			"/Zc:__cplusplus",
			"/std:c++latest",
			"/bigobj",
			"-Wno-unused-command-line-argument",
			{ force = true }
		)

		local xdg = os.getenv("XDG_DATA_HOME") or path.join(os.getenv("HOME") or "~", ".local/share")
		local splat =
			path.join(os.getenv("GEODE_CROSS_TOOLS") or path.join(xdg, "Geode/cross-tools/clang-msvc-sdk"), "splat")
		if os.isdir(splat) then
			for _, dir in ipairs({
				path.join(splat, "crt/include"),
				path.join(splat, "sdk/include/ucrt"),
				path.join(splat, "sdk/include/shared"),
				path.join(splat, "sdk/include/um"),
				path.join(splat, "sdk/include/winrt"),
			}) do
				target:add("cxflags", "-imsvc" .. dir, { force = true })
			end
		end
	end

	local sdk_path = os.getenv("GEODE_SDK") or ""
	if sdk_path ~= "" and os.isdir(sdk_path) then
		target:add("includedirs", {
			path.join(sdk_path, "loader/include"),
			path.join(sdk_path, "loader/include/Geode/cocos/include"),
			path.join(sdk_path, "loader/include/Geode/cocos/extensions"),
			path.join(sdk_path, "loader/include/Geode/fmod"),
		})
		target:add("defines", {
			"NOMINMAX",
			"_HAS_ITERATOR_DEBUGGING=0",
			"MAT_JSON_DYNAMIC=1",
			"GEODE_GD_VERSION=2.2081",
			"GEODE_COMP_GD_VERSION=22081",
			'GEODE_GD_VERSION_STRING="2.2081"',
		})
	end
end)

on_config(function(target)
	local mod_dir = target:scriptdir()
	local mode = get_config("mode") or "release"
	local build_dir = path.join(mod_dir, "build", "cmake-" .. mode)
	local ccjson_path = path.join(build_dir, "compile_commands.json")

	if not os.isfile(ccjson_path) then
		local sdk_path = os.getenv("GEODE_SDK") or ""
		if sdk_path == "" or not os.isdir(sdk_path) then
			return
		end

		local mod_id = target:data("geode.mod_id") or target:name()
		local sources = {}
		for _, pat in ipairs(table.wrap(target:get("files") or {})) do
			local abs = path.is_absolute(pat) and pat or path.join(mod_dir, pat)
			for _, f in ipairs(os.files(abs)) do
				table.insert(sources, path.absolute(f))
			end
		end
		if #sources == 0 then
			return
		end

		local cmake_sources = ""
		for _, f in ipairs(sources) do
			cmake_sources = cmake_sources .. string.format('    "%s"\n', f:gsub("\\", "/"))
		end
		local pkg_cmake = xmake_packages_cmake(target)
		io.writefile(
			path.join(mod_dir, "CMakeLists.txt"),
			string.format(
				[[# Generated by geode-xmake — do not edit by hand
cmake_minimum_required(VERSION 3.25 FATAL_ERROR)
project(%s)

set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
add_subdirectory("%s" "${CMAKE_BINARY_DIR}/geode-sdk")

add_library(${PROJECT_NAME} SHARED
%s)
target_compile_features(${PROJECT_NAME} PUBLIC cxx_std_23)

setup_geode_mod(${PROJECT_NAME})
%s]],
				mod_id,
				sdk_path:gsub("\\", "/"),
				cmake_sources,
				pkg_cmake
			)
		)

		os.mkdir(build_dir)
		local cmake_args = {
			mod_dir,
			"-B",
			build_dir,
			"-DCMAKE_BUILD_TYPE=" .. ((mode == "debug") and "Debug" or "Release"),
		}
		if os.host() == "linux" then
			local xdg = os.getenv("XDG_DATA_HOME") or path.join(os.getenv("HOME") or "~", ".local/share")
			local cross = os.getenv("GEODE_CROSS_TOOLS") or path.join(xdg, "Geode/cross-tools/clang-msvc-sdk")
			local tc_file = path.join(cross, "clang-cl-msvc.cmake")
			local splat = path.join(cross, "splat")
			if os.isfile(tc_file) and os.isdir(splat) then
				table.insert(cmake_args, "-DCMAKE_TOOLCHAIN_FILE=" .. tc_file)
				table.insert(cmake_args, "-DSPLAT_DIR=" .. splat)
				table.insert(cmake_args, "-DHOST_ARCH=x86_64")
			end
		end

		cprint("${cyan}[geode.mod] Running cmake configure for compile_commands.json...")
		os.execv("cmake", cmake_args)
	end

	if os.isfile(ccjson_path) then
		try({
			function()
				import("core.base.json")
				local entries = json.decode(io.readfile(ccjson_path))
				if entries then
					for _, entry in ipairs(entries) do
						if entry.file and entry.file:find(mod_dir, 1, true) then
							for imsvc_dir in entry.command:gmatch("-imsvc([^%s]+)") do
								if imsvc_dir:find(build_dir, 1, true) then
									target:add("cxflags", "-imsvc" .. imsvc_dir, { force = true })
								end
							end
							break
						end
					end
				end
			end,
			catch({
				function(err)
					cprint("${yellow}[geode.mod] Could not parse cmake compile_commands.json: %s", tostring(err))
				end,
			}),
		})

		os.cp(ccjson_path, path.join(mod_dir, "build", "compile_commands.json"))
	end
end)

on_build(function(target)
	local sdk_path = os.getenv("GEODE_SDK") or ""
	assert(
		sdk_path ~= "" and os.isdir(sdk_path),
		"[geode.mod] GEODE_SDK environment variable must point to your Geode SDK checkout"
	)

	local mod_dir = target:scriptdir()
	local mod_id = target:data("geode.mod_id") or target:name()
	local mode = get_config("mode") or "release"
	local build_type = (mode == "debug") and "Debug" or "Release"
	local build_dir = path.join(mod_dir, "build", "cmake-" .. mode)

	local sources = {}
	for _, pat in ipairs(table.wrap(target:get("files") or {})) do
		local abs = path.is_absolute(pat) and pat or path.join(mod_dir, pat)
		for _, f in ipairs(os.files(abs)) do
			table.insert(sources, path.absolute(f))
		end
	end
	assert(#sources > 0, "[geode.mod] No source files found for " .. mod_id)

	local conf = target:extraconf("rules", "geode.mod") or {}
	local dont_install_str = conf.install == false and " DONT_INSTALL" or ""

	local cmake_sources = ""
	for _, f in ipairs(sources) do
		cmake_sources = cmake_sources .. string.format('    "%s"\n', f:gsub("\\", "/"))
	end
	local pkg_cmake = xmake_packages_cmake(target)
	io.writefile(
		path.join(mod_dir, "CMakeLists.txt"),
		string.format(
			[[# Generated by geode-xmake — do not edit by hand
cmake_minimum_required(VERSION 3.25 FATAL_ERROR)
project(%s)

set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
add_subdirectory("%s" "${CMAKE_BINARY_DIR}/geode-sdk")

add_library(${PROJECT_NAME} SHARED
%s)
target_compile_features(${PROJECT_NAME} PUBLIC cxx_std_23)

setup_geode_mod(${PROJECT_NAME}%s)
%s]],
			mod_id,
			sdk_path:gsub("\\", "/"),
			cmake_sources,
			dont_install_str,
			pkg_cmake
		)
	)

	os.mkdir(build_dir)
	local cmake_args = {
		mod_dir,
		"-B",
		build_dir,
		"-DCMAKE_BUILD_TYPE=" .. build_type,
	}
	if os.host() == "linux" then
		local xdg = os.getenv("XDG_DATA_HOME") or path.join(os.getenv("HOME") or "~", ".local/share")
		local cross = os.getenv("GEODE_CROSS_TOOLS") or path.join(xdg, "Geode/cross-tools/clang-msvc-sdk")
		local tc_file = path.join(cross, "clang-cl-msvc.cmake")
		local splat = path.join(cross, "splat")
		if os.isfile(tc_file) and os.isdir(splat) then
			table.insert(cmake_args, "-DCMAKE_TOOLCHAIN_FILE=" .. tc_file)
			table.insert(cmake_args, "-DSPLAT_DIR=" .. splat)
			table.insert(cmake_args, "-DHOST_ARCH=x86_64")
		end
	end

	cprint("${cyan}[geode.mod] Configuring %s...", mod_id)
	os.execv("cmake", cmake_args)

	local jobs = math.max(1, os.cpuinfo().ncpu or 1)
	cprint("${cyan}[geode.mod] Building %s (%d jobs)...", mod_id, jobs)
	os.execv("cmake", {
		"--build",
		build_dir,
		"--config",
		build_type,
		"-j",
		tostring(jobs),
	})

	local ccjson = path.join(build_dir, "compile_commands.json")
	if os.isfile(ccjson) then
		os.cp(ccjson, path.join(mod_dir, "build", "compile_commands.json"))
	end

	local geode_file = path.join(build_dir, mod_id .. ".geode")
	if os.isfile(geode_file) then
		cprint("${green}[geode.mod] Created %s", geode_file)
	end
end)

on_clean(function(target)
	local mod_dir = target:scriptdir()
	local mode = get_config("mode") or "release"
	local build_dir = path.join(mod_dir, "build", "cmake-" .. mode)
	if os.isdir(build_dir) then
		os.rmdir(build_dir)
		cprint("${cyan}[geode.mod] Cleaned %s", build_dir)
	end
end)

rule_end()
